"""add_permission_system_tables

Revision ID: 31697903fa71
Revises: n4o5p6q7r8s9
Create Date: 2026-03-13 00:59:51.012757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '31697903fa71'
down_revision: Union[str, Sequence[str], None] = 'n4o5p6q7r8s9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_data_masks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('data_domain_id', sa.Integer(), nullable=True),
    sa.Column('mask_action', sa.Enum('keep', 'hide', 'remove', 'range', 'truncate', 'partial', 'rank', 'aggregate', 'replace', 'noise', 'show', 'label_only', name='maskaction'), nullable=False),
    sa.Column('mask_params', mysql.JSON(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_domain_id'], ['data_domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_mask_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('data_domain_id', sa.Integer(), nullable=True),
    sa.Column('mask_action', sa.Enum('keep', 'hide', 'remove', 'range', 'truncate', 'partial', 'rank', 'aggregate', 'replace', 'noise', 'show', 'label_only', name='maskaction'), nullable=False),
    sa.Column('mask_params', mysql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_domain_id'], ['data_domains.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_output_masks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('data_domain_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('mask_action', sa.Enum('keep', 'hide', 'remove', 'range', 'truncate', 'partial', 'rank', 'aggregate', 'replace', 'noise', 'show', 'label_only', name='maskaction'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_domain_id'], ['data_domains.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'data_domain_id', 'field_name', name='uq_role_output_mask')
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_type', sa.Enum('skill_publish', 'scope_change', 'mask_override', 'schema_approval', name='approvalrequesttype'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'conditions', name='approvalstatus'), nullable=False),
    sa.Column('conditions', mysql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_table', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('old_values', mysql.JSON(), nullable=True),
    sa.Column('new_values', mysql.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('approve', 'reject', 'add_conditions', name='approvalactiontype'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handoff_schema_caches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('upstream_skill_id', sa.Integer(), nullable=True),
    sa.Column('downstream_skill_id', sa.Integer(), nullable=True),
    sa.Column('task_type_hash', sa.String(length=64), nullable=True),
    sa.Column('schema_json', mysql.JSON(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('incomplete_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['downstream_skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['upstream_skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_table('handoff_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('upstream_skill_id', sa.Integer(), nullable=True),
    sa.Column('downstream_skill_id', sa.Integer(), nullable=True),
    sa.Column('template_type', sa.Enum('standard', 'l3_mask', 'multi_upstream', name='handofftemplatetype'), nullable=False),
    sa.Column('schema_fields', mysql.JSON(), nullable=True),
    sa.Column('excluded_fields', mysql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['downstream_skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['upstream_skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_mask_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('mask_action', sa.Enum('keep', 'hide', 'remove', 'range', 'truncate', 'partial', 'rank', 'aggregate', 'replace', 'noise', 'show', 'label_only', name='maskaction'), nullable=False),
    sa.Column('mask_params', mysql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_output_schemas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'approved', name='schemastatus'), nullable=False),
    sa.Column('schema_json', mysql.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('publish_scope', sa.Enum('self_only', 'same_role', 'cross_role', 'org_wide', name='publishscope'), nullable=False),
    sa.Column('default_data_scope', mysql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id')
    )
    op.create_table('handoff_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upstream_skill_id', sa.Integer(), nullable=True),
    sa.Column('downstream_skill_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('cache_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', mysql.JSON(), nullable=True),
    sa.Column('status', sa.Enum('success', 'incomplete', 'failed', name='handoffexecutionstatus'), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('executed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cache_id'], ['handoff_schema_caches.id'], ),
    sa.ForeignKeyConstraint(['downstream_skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['handoff_templates.id'], ),
    sa.ForeignKeyConstraint(['upstream_skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_policy_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_policy_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('callable', sa.Boolean(), nullable=True),
    sa.Column('data_scope', mysql.JSON(), nullable=True),
    sa.Column('output_mask', mysql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['skill_policy_id'], ['skill_policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_policy_id', 'position_id', name='uq_role_policy_override')
    )
    op.create_table('skill_agent_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_policy_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('upstream', 'downstream', name='connectiondirection'), nullable=False),
    sa.Column('connected_skill_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connected_skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['skill_policy_id'], ['skill_policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_policy_id', 'direction', 'connected_skill_id', name='uq_skill_agent_connection')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key('fk_ws_model_config', 'workspaces', 'model_configs', ['model_config_id'], ['id'], ondelete='SET NULL')
    op.create_index('workspace_id', 'workspace_tools', ['workspace_id', 'tool_id'], unique=True)
    op.create_index('workspace_id', 'workspace_skills', ['workspace_id', 'skill_id'], unique=True)
    op.alter_column('web_apps', 'html_content',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.create_index('uq_user_saved_skill', 'user_saved_skills', ['user_id', 'skill_id'], unique=True)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_created_by_id', 'tasks', ['created_by_id'], unique=False)
    op.create_index('ix_tasks_assignee_id', 'tasks', ['assignee_id'], unique=False)
    op.alter_column('skill_versions', 'system_prompt',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.create_index('skill_id', 'skill_tools', ['skill_id', 'tool_id'], unique=True)
    op.drop_table('skill_agent_connections')
    op.drop_table('role_policy_overrides')
    op.drop_table('handoff_executions')
    op.drop_table('skill_policies')
    op.drop_table('skill_output_schemas')
    op.drop_table('skill_mask_overrides')
    op.drop_table('handoff_templates')
    op.drop_table('handoff_schema_caches')
    op.drop_table('approval_actions')
    op.drop_table('permission_audit_logs')
    op.drop_table('approval_requests')
    op.drop_table('role_output_masks')
    op.drop_table('role_mask_overrides')
    op.drop_table('global_data_masks')
    # ### end Alembic commands ###
